### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by jzielke-nli** [nextcloud/passman-android#49] opened 2018-03-01 11:53 UTC
Unfortunately I'm having the same problem like stated here:

https://github.com/nextcloud/passman-android/issues/13

I'm using latest passman app on nextcloud 13 from this repo and the android app on my galaxy s8.

The chrome extension runs just fine but on android using an app-password because of 2factor auth I get network error after entering my https-url and my credentials. However I see my password safe being displayed, just can't open it.

Certificate Chain is fine and fully served by the server as stated by qualys test with A-rating.

- Nextcloud 13
- Android 7
- Passman 2.1.5
- Android Passman latets from Play Store

**Comment by brantje** [comment] 2018-03-01 11:58
Hi, 
Why do you open an issue, if it already exists?
Closing since it's a duplicate of #13

**Closed by brantje** 2018-03-01 11:58 UTC

**Comment by jzielke-nli** [comment] 2018-03-01 12:03
@brantje Because as stated in #13 the error was not using an app -password

> You were right - I needed to use my APP password as I had setup 2nd factor authentication.

Since this is not the case here I think this issues lies more in incompatiblity with latest passman commit here and the android app, which hasn't been updated for some months now except language additions.

**Comment by brantje** [comment] 2018-03-01 12:05
Hi @jzielke-nli,
That topic is all about network errors / ssl problems and such.
The API didn't change so that should be working (tm).
Do you get any errors in the app?

**Comment by jzielke-nli** [comment] 2018-03-01 12:10
Except the "network error" after tapping my password safe no. Since it's in an alpha state I think there's not much chance for me to debug on my phone. I'd be willing to create a password safe for testing and sending someone the credentials if that helps.

- Julian
